### ISSUE TITLE
[matklad.rust-analyzer] 'releaseTag` is not properly populated

### ISSUE THREAD

**Issue by bryphe** [open-vsx/publish-extensions#106]
Hi, thanks for the great work on open-vsx.org!

The `rust-analyzer` extension has a `releaseTag` property in the `package.json`:
https://github.com/rust-analyzer/rust-analyzer/blob/5ebf92cd0ed4be97fe0ca5bffefbe292db1ec4cf/editors/code/package.json#L9

During the build - at least the one published on the Visual Studio marketplace - the `releaseTag` actually has a value populated, ie: `"releaseTag": "2020-08-04"`. This happens in a separate distribution script: https://github.com/rust-analyzer/rust-analyzer/blob/3d799b66df8550a21523d42116a9b83116aa92d8/xtask/src/dist.rs

The extension uses the `releaseTag` to decide what sort of binary to pick up for `rust-analyzer`, and when it's null - it doesn't download a binary at all: https://github.com/rust-analyzer/rust-analyzer/blob/56ade20380a028026eeb71af2a8a81e37ede7efb/editors/code/src/main.ts#L153 

This causes the language server binary to not be downloaded automatically, requiring more manual set-up.

Related to the work done in #41 

Maybe there is a way to pick up the 'latest' artifact in the `rust-analyzer` field and populate this field automatically, from the build step? https://github.com/open-vsx/publish-extensions/blob/0364450ef9c6651be7e51da040bde2bc295e2382/extensions.json#L494

**Comment by spoenemann** [comment]
Maybe it would be better to ask the maintainers of this extension whether they would take over publishing to Open VSX. @bryphe would you create an issue at their repository and ask?

Anyway, once we have a correct bundle published, we should delete the malfunctioning versions.

**Comment by jankeromnes** [comment]
Good catch, many thanks @bryphe!

It would indeed be much better if this extension can be published to OpenVSX by the original authors (they only need to run `npx ovsx publish`, without installing any dependency) instead of by us (generic OpenVSX bot user) in this rather basic publishing CI repo.

See also a previous publish issue we faced and had to work around: https://github.com/open-vsx/publish-extensions/issues/41

**Comment by bryphe** [comment]
@jankeromnes @spoenemann - thanks for looking at this!

It looks like there was an issue already on the repo that was closed: https://github.com/rust-analyzer/rust-analyzer/issues/4936

**Comment by jankeromnes** [comment]
Good point @bryphe, the request to publish to OpenVSX was indeed closed, because we ended up publishing the extension from our basic publishing CI here (instead of from the official extension repository).

However, I would argue that any problem revealed in our CI's automated publishing reveals something that is particular to a specific extension (because the other extensions generally work without requiring any tweaks), and is one more argument in favor of having the original authors do the publishing instead of us reverse-engineering how the extension should in fact be published (e.g. what extra steps are there, are we forgetting some specific command or tool or build step, etc. otherwise we risk accidentally publishing a broken/incomplete extension which would be highly disruptive to consumers of the extension).
