### ISSUE TITLE
[matklad.rust-analyzer] Cannot activate rust-analyzer: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#129]
Originally reported here: https://community.gitpod.io/t/rust-analyzer-extension-problem/1703

**Comment by carterisonline** [comment]
I'm also receiving an error relating to this:

> `Cannot activate rust-analyzer: Object.fromEntries is not a function`

(occurs when attempting to install for the _current project_)

> `Cannot activate rust-analyzer: Command "rust-analyzer.onEnter" already has handler`

(occurs when attempting to install for the _user_)

Maybe this is possibly caused by gitlab's included plugins' configuration? I'm slightly familar with Javascript, so I'll try to scope out the issue for now.

**Comment by jankeromnes** [comment]
Ah, I think this problem occurs because Gitpod's IDE (Theia) is still running Node.js v10.

I think Theia upstream has been upgraded to Node.js v12 LTS, and Gitpod will soon upgrade to the latest Theia version, which should resolve this problem. (Note: Gitpod Self-Hosted should already no longer have this bug.)

**Comment by filiptronicek** [comment]
Gitpod is not using Theia anymore, and the default Node version is 16 as of today. Should be good to go, but the extension won't work because of #527.
