### ISSUE TITLE
[golang.go] latest version is not being published

### ISSUE THREAD

**Issue by Surendrajat** [open-vsx/publish-extensions#200]
Even though the given branch has version 0.18.0, it's not updating.

**Comment by andhet** [comment]
Golang.go was updated on 2020-11-02 to 0.18.1, which was uploaded to open-vsx.org 3 days ago, so I assume that this problem is solved and ticket can be closed.

**Comment by Surendrajat** [comment]
I can see it's been updated but if you see version history, it's not being updated continuously. Maybe there is an issue that prevents certain versions from being uploaded.

**Comment by andhet** [comment]
The configuration for publishing is not based on a fixed version, but on the "latest" branch. (Seems to be related to https://github.com/golang/vscode-go/issues/222)
Version 0.18.0 was released on 23rd October. When I look at the log output from the publishing extensions action defined here on 28rd October the latest branch was still pointing to the former 0.17.2 release. Hence I assume, that the golang.go crew forgot to update their latest branch to the new release. (Based on the assumption that this "latest" branch thing is not a github build-in feature, but some manual thing. I'm not familiar with github yet, sorry.)

**Comment by Surendrajat** [comment]
@andhet You are right about manual updating. There is no such feature. However, as you can see vscode-go has this commit on 24th Oct golang/vscode-go@d27880e35ef59ce113c96ebccf37aa41dca471ea but the CI logs for 25th, 26th and so on.. don't seem to be picking it.

**Comment by andhet** [comment]
Yes, you're of course right. And I don't understand it. I have looked to the publish-extensions.js script here and there is no magic happening; just a clone and than a checkout to switch to the latest branch. No, errors were logged during these operations. It seems for me that the version after that clone was still 0.17.2, which isn't possible given the commit history of the latest branch of golang/vscode-go. Maybe I'm just overseeing something, which is absolutely possible considering that my javascript knowledge is more than limited.
I'm afraid, but I'm no help here. Maybe I can invest some time next weekend, because I must confess that the Sherlock in me is triggered by this riddle, but maybe some of the maintainers here have some time to look at this before.
In the meantime I'm starting to watch the vscode-go project for new releases until someone found the reason for this problem here. Maybe the problem will reoccur at the next release.

**Comment by andhet** [comment]
Just a quick info here. 0.19.0 was released 2 hours ago and is already available on the Visual Studio marketplace. Latest branch is currently still pointing to 0.18.1.

**Comment by Surendrajat** [comment]
Yeah. Seems like they are delaying the update commit so let's wait and see. Usually, it's very little difference. I wonder if they've forgotten about this branch :rofl:

**Comment by jankeromnes** [comment]
Hi @Surendrajat and @andhet,

> Just a quick info here. 0.19.0 was released 2 hours ago and is already available on the Visual Studio marketplace.

That's why it's much better when the extension's owners/maintainers publish to OpenVSX directly. (It's as simple as setting up a [OVSX_PAT](https://open-vsx.org/user-settings/tokens) token and running `npx ovsx publish`).

But since this wasn't set up yet for `golang.go`, we took over the publishing in the interim, using this repository. `golang.go` publishing is currently configured like so:

https://github.com/open-vsx/publish-extensions/blob/4479586868b70ecb2665e9b2a5a3bcaae2ba19a4/extensions.json#L481-L485

This means that, every night at [03:03 UTC](https://github.com/open-vsx/publish-extensions/blob/fe841aaf9393fda85d14fda5b70f5f23ef4e7035/.github/workflows/publish-extensions.yml#L3-L6), our publishing workflow will run something like:

```
git clone https://github.com/golang/vscode-go
cd vscode-go
git checkout latest
npm install
npx ovsx publish
```

While this isn't ideal, it's a good compromise solution until the maintainers of `golang.go` can take over the publishing (honestly the `npx ovsx publish` call can even be added as just one extra line to an existing VSCode Marketplace publishing process -- there are no extra dependencies required).

**Comment by jankeromnes** [comment]
If the `latest` branch is no longer maintained, we could also amend the configuration like so, in order to re-publish the latest official `.vsix` release directly:

```json
{
  "id": "golang.Go",
  "download": "https://github.com/golang/vscode-go/releases/download/v0.19.0/go-0.19.0.vsix",
  "version": "0.19.0"
},
```

**Comment by andhet** [comment]
Hi jankeromnes 
Yes, that would be probably the preferred way, but have a look to the issue [Publish extension on open-vsx.org](https://github.com/golang/vscode-go/issues/222). The latest branch was their solution for publishing to open-vsx. I think that they still support their latest branch, but maybe forget regularly about it.
I've found their release job/action https://github.com/golang/vscode-go/blob/master/.github/workflows/release.yml containing a TODO to automatically update their latest branch. But yes, it would be better to enhance this file so that it will deploy to open-vsx directly.

**Comment by andhet** [comment]
@Surendrajat 
The github repo is just a mirror repo. The canonical repo is "https://go.googlesource.com/vscode-go/".  
So I have a wild guess about your observation:
> @andhet You are right about manual updating. There is no such feature. However, as you can see vscode-go has this commit on 24th Oct [golang/vscode-go@d27880e](https://github.com/golang/vscode-go/commit/d27880e35ef59ce113c96ebccf37aa41dca471ea) but the CI logs for 25th, 26th and so on.. don't seem to be picking it.

This commit was done and pushed to the canonical repository, but wasn't pushed to the github mirror. Hence the release was never published to open-vsx. Ok, might be a very wild guess, but the best I currently have.
Anyhow. jankeromnes is right. The best way would be releasing directly to open-vsx and maybe we should file a new issue to ask kindly to do so.

**Comment by Surendrajat** [comment]
@andhet It might be but I suspect they have some sort of continuous mirror service in place for all of the repos. Anyways, they still haven't updated this yet: https://go.googlesource.com/vscode-go/+log/refs/heads/latest

Agree with @jankeromnes but I think we should open an issue after open-vsx's migration to eclipse and all, otherwise it will again stop updating.

**Comment by andhet** [comment]
@Surendrajat 
You are probably right. But maybe, (very small maybe) there is just a TODO, saying "support automatic mirroring of latest branch". Ok, I know. Little bit absurd... But hey. I've already seen code like
`public static final int TEN = 100`.

Yeah, let's wait for the migration. :)

**Comment by jankeromnes** [comment]
> Agree with @jankeromnes but I think we should open an issue after open-vsx's migration to eclipse and all, otherwise it will again stop updating.

> Yeah, let's wait for the migration. :)

I'm not sure the migration would have an impact on an OpenVSX publishing script, but I agree that it's probably safer to wait for after the migration.

Meanwhile, I've updated the configuration as suggested in https://github.com/open-vsx/publish-extensions/issues/200#issuecomment-734152749 to at least auto-publish `0.19.0`: https://github.com/open-vsx/publish-extensions/pull/234/commits/25d092de06d8a3b8ed9dd0d69744310b777897f8

**Comment by andhet** [comment]
@jankeromnes 
Thank you. :)

**Comment by Surendrajat** [comment]
Ping.
Is it a right time to get rid of `Bump golang.go` commits? :)

**Comment by Surendrajat** [comment]
> microsoft/vscode-go is archived now, so we should probably remove that one and keep golang.Go... right?

Right. It has been moved to golang org.

But what I really meant was to ask maintainers to automate this step now and stop bumping manually :)
Transitions to eclipse fdn is also over now.

**Comment by andhet** [comment]
https://github.com/golang/vscode-go/issues/1177

**Comment by andhet** [comment]
So, they won't publish directly. It would be ok for them to keep the latest branch up to date. (At the moment it is still pointing to an old version.) So should we revert commit [25d092d](https://github.com/open-vsx/publish-extensions/commit/25d092de06d8a3b8ed9dd0d69744310b777897f8) or should we keep a fixed version number, which has to be updated manually?

**Comment by Surendrajat** [comment]
It's sad, and the maintenance argument doesn't really hold here, but I don't think that commit should be reverted. It will start the loop again when they don't update, and we have to ping them again.
Instead, I'd like to see these `Bump xyz…` PRs automated with some script or bot instead of manually updating those. At least, for extensions which have GitHub releases.

**Comment by andhet** [comment]
I agree, that the commit shouldn't be reverted.
Where do you see that? And would this filter out release candidates? There must be a reason why a fix version number is recommended.

**Comment by Surendrajat** [comment]
I saw this commit https://github.com/open-vsx/publish-extensions/commit/7377ee89906fef2259f5b28891d8cb3be16cbce2 and I think this is related :)

**Comment by jankeromnes** [comment]
Thanks again for opening the request! A bit sad about the outcome, but we can indeed continue publishing any available `.vsix` from here.

Also, as you've pointed out, the process of upgrading is nearly fully automated:

- `node add-extension REPO_URL` will now automatically pick a `.vsix` release from GitHub if available

- `node upgrade-extensions` goes through the entire list, and bumps the configs when a new release is available

We still run `node upgrade-extensions` and create commits manually, but we could definitely set up a cronjob that does that and sends a Pull Request every week. 🤖

**Comment by Surendrajat** [comment]
@jankeromnes @andhet please feel free to close this now. Thanks for all your nice work on open-vsx!

**Comment by andhet** [comment]
> I saw this commit [7377ee8](https://github.com/open-vsx/publish-extensions/commit/7377ee89906fef2259f5b28891d8cb3be16cbce2) and I think this is related :)
Nice, haven't seen that. :)

@jankeromnes 
Shall we than set up the automatically cronjob? I would favour this approach over a build from their latest branch. 
What is needed for that? A yaml file under .github/workflows? (Sorry, but I don't know how such things are working in github. I'm used to Bitbucket and Jenkins.)

**Comment by andhet** [comment]
I think this issue can be closed now. :)

**Comment by Surendrajat** [comment]
@andhet thanks for automating it. Feel free to close anytime after Sunday :)

**Comment by andhet** [comment]
@Surendrajat 
I can't close it. Are you not yourself able to close this tasks, because you have created it?

**Comment by Surendrajat** [comment]
Sure. I can.
