### ISSUE TITLE
matklad.rust-analyzer is out of date

### ISSUE THREAD

**Issue by SimonSapin** [open-vsx/publish-extensions#342]
https://open-vsx.org/extension/matklad/rust-analyzer currently lists version 0.2.563 as "latest", whereas https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer has version 0.2.591.

It looks like the last update was made by @jankeromnes in https://github.com/open-vsx/publish-extensions/pull/333. Are such updates automated? Is making a new one blocked on something?

----

For context, I reported a bug https://github.com/rust-analyzer/rust-analyzer/issues/8792 upstream and only when investigating that did I realize that [the Archlinux build of Code OSS](https://archlinux.org/packages/community/x86_64/code/) uses open-vsx.org instead of Microsoft’s Marketplace.

rust-analyzer’s development is rather active these days, so it can be misleading to have Code OSS say "All extensions are up to date" when in fact an old, buggy version is being used. If automating updates turns out difficult it might be better to not have this extension on open-vsx at all rather than have an old version that claims to be the latest.

**Comment by jankeromnes** [comment]
Salut Simon ! 👋 😁

> It looks like the last update was made by @jankeromnes in #333. Are such updates automated? Is making a new one blocked on something?

Whoops, good catch. These updates are indeed automated, but it looks like the automation started failing 2-3 weeks ago:

https://github.com/open-vsx/publish-extensions/actions/workflows/upgrade-extensions.yml

Will investigate & fix.

---

On a side note, this may be a good time to re-consider publishing to OpenVSX from the `rust-analyzer` repository itself (see also https://github.com/rust-analyzer/rust-analyzer/issues/4936, https://github.com/rust-analyzer/rust-analyzer/issues/5509 and https://github.com/rust-analyzer/rust-analyzer/issues/5688).

The fix is actually as easy as adding a single at the bottom of [.github/workflows/release.yaml](https://github.com/rust-analyzer/rust-analyzer/blob/77518991b83dc8673f5c25cf252af7956469e554/.github/workflows/release.yaml#L318-L322). The line is:

```
&& npx ovsx publish --pat ${{ secrets.OVSX_TOKEN }} --packagePath ../../dist/rust-analyzer.vsix
```

**Comment by jankeromnes** [comment]
Update: Fixed in https://github.com/open-vsx/publish-extensions/pull/343/files

Latest `matklad.rust-analyzer` should get auto-published tonight (along with a bunch of other upgrades).

Thanks for reporting the broken auto-upgrades!

**Comment by jankeromnes** [comment]
> Thanks for the quick fix!

You're very welcome! 🙌

> I see that #342 is submitted from your personal account (rather than some bot account). Does it mean you make PRs like this manually?

So,

- anyone can upgrade all extensions in `extensions.json` by simply running `node upgrade-extensions` (see [script](https://github.com/open-vsx/publish-extensions/blob/master/upgrade-extensions.js))
- in #342 I fixed the script, and ran it manually once to confirm that it works
- (when it works) the script [also runs](https://github.com/open-vsx/publish-extensions/blob/12204860943830e535e1f17f000c59d607f5face/.github/workflows/upgrade-extensions.yml#L25) automatically [every sunday](https://github.com/open-vsx/publish-extensions/blob/12204860943830e535e1f17f000c59d607f5face/.github/workflows/upgrade-extensions.yml#L6-L8), creating weekly automated PRs like this one: https://github.com/open-vsx/publish-extensions/pull/308
