### ISSUE TITLE
Remove bung87 extensions from publish script

### ISSUE THREAD

**Issue by brianking** [open-vsx/publish-extensions#345]
The following 2 extensions can be removed, as the author is taking over publishing.

https://github.com/bung87/vscode-rails
https://github.com/bung87/vscode-gemfile

More details:
https://github.com/EclipseFdn/open-vsx.org/issues/491

**Comment by bung87** [comment]
wait , open-vsx has script automatic publish ? then I dont need manually publish myself ?

**Comment by jankeromnes** [comment]
Hi @bung87!

Yes, OpenVSX has some cheap auto-publishing in place, but only for when nothing better is possible.

This "automation" basically just `git clone`s an extension repository and runs `npx ovsx publish` in it every night. But this isn't ideal, because:
- it can accidentally publish work-in-progress state (the first uploaded version remains forever)
- it can publish broken artifacts (if your extension requires any sort of build commands, the automation won't run them, so the uploaded extension is probably going to be missing some components / be broken)

That's why it's always better when the author/maintainer can run `npx ovsx publish` themselves.

But please let us know if you'd like any help with that! (Tip: If you already have a GitHub Action that publishes to VSCode Marketplace, you can simply add `npx ovsx plubish --pat=OVSX_PAT` after it -- the token can be generated [here](https://open-vsx.org/user-settings/tokens).)

**Comment by bung87** [comment]
ok, get it, I can simply maintain publish state myself.

**Comment by brianking** [comment]
@jankeromnes It seems like this is good to remove now.
