### ISSUE TITLE
ESLint shouldn't be on the "don't update" list

### ISSUE THREAD

**Issue by heyheyhello** [open-vsx/publish-extensions#363]
Hello,

First, thanks for all your work on this project! I noticed yesterday that the ESLint version in VSCodium is very old at Oct 2020 so I checked out this repo and starting updating the extension.json - only after I noticed that vscode-eslint is on your block list:

https://github.com/open-vsx/publish-extensions/commit/04b9d475d20b93f59008078e77d9adbda1206ffc

The rationale was that all releases have been pre-releases/insider releases.

I understand that vscode-eslint hasn't updated their _tag_ (the nice green "Latest Release" button on the repo homepage) but they still do releases: https://github.com/microsoft/vscode-eslint/tags

<img width="528" alt="Screen Shot 2021-06-17 at 10 34 51 AM" src="https://user-images.githubusercontent.com/44614862/122446588-b0306c80-cf57-11eb-8215-a6a71a623177.png">

The latest release would be 2.1.23. The latest VSCode extension (normal VSCode, not Insider VSCode) is 2.1.20. Which is fair since it's only been 7 days since something newer is out.

Considering vscode-eslint 2.1.20 has been available to its 14.9M users can we also consider it safe to update? It has good new features (like not needing to reload the whole window for a simple config change) 😄 Thanks!

**Comment by jankeromnes** [comment]
Hi @heyheyhello! Wow, many thanks for the great catch. I suppose the [Releases](https://github.com/microsoft/vscode-eslint/releases) page says "Insider" everywhere, but actually most of these are now "stable", right?

I totally agree that the latest stable version should be published. I'll adjust our auto-publish pipeline to make this happen. (Also, sorry for the very late response, as this issue seems to have slipped through unnoticed 🙈)
