### ISSUE TITLE
warning when `npm install`

### ISSUE THREAD

**Issue by playgithub** [open-vsx/publish-extensions#408]
## Env
`npm install` in the root of this repo

## Log
```
$ npm install
npm WARN deprecated typed-rest-client@1.8.5: 1.8.5 contains changes that are not compatible with Node 6
```

**Comment by JanKoehnlein** [comment]
/schedule
/team meta
/assign @jankeromnes 

I've assigned @jankeromnes as I know he's going to work on it.
In the long run the open VSX tasks should go to the IDE team.

**Comment by filiptronicek** [comment]
Hi @playgithub, sorry this took so long. I have tried to replicate the issue but can't: the only warning that I get when switching to Node 6 is an invalid license expression, but that is because Node 6 is using an old version of the license ID database, which is not something present in newer versions of Node. 

I'm closing this for now, if it comes up again for you please let me know 😃
