### ISSUE TITLE
The `amodio.tsl-problem-matcher` Can't Be Published 

### ISSUE THREAD

**Issue by manuth** [open-vsx/publish-extensions#567]
As far as I can see, the `amodio.tsl-problem-matcher` extension can't be published by GitHub Actions.
However, I don't really understand what's causing it to fail.

Is it not working because the `amodio` namespace already exists?

**Comment by filiptronicek** [comment]
I recently reached out to the OpenVSX guys to see what's up with this one. It seems that this was some weird bug which wasn't appearing in any of the logs, it randomly started publishing successfully some weeks ago. Closing since this is (hopefully) not an issue anymore: https://open-vsx.org/extension/amodio/tsl-problem-matcher
