### ISSUE TITLE
Jupyter extension: Pre-release set to latest version

### ISSUE THREAD

**Issue by benz0li** [open-vsx/publish-extensions#569]
https://open-vsx.org/extension/ms-toolsai/jupyter/2022.3.1000752054 should not have been published as https://open-vsx.org/extension/ms-toolsai/jupyter/latest [for now at least].

---

In comparison:

**ESLint**  
https://open-vsx.org/extension/dbaeumer/vscode-eslint/latest is https://open-vsx.org/extension/dbaeumer/vscode-eslint/2.2.2.  
👉 v2.2.3 (pre-release) has been out since mid January but is not published on Open VSX.

**Python**  
https://open-vsx.org/extension/ms-python/python/latest is https://open-vsx.org/extension/ms-python/python/2022.2.1924087327  
👉 2022.3.n{10} (pre-release) has been out for some time but is not published on Open VSX.

@filiptronicek In my opinion publishing of ESLint and Python extension is handled correctly, but not for Jupyter extension.

---

Does https://github.com/open-vsx/publish-extensions/commit/9fe3cf47613d62675f742b33aa38ad258785ab89 work correctly for [ms-toolsai.jupyter](https://github.com/microsoft/vscode-jupyter)?

**Comment by benz0li** [comment]
See https://github.com/eclipse/openvsx/issues/436 for previous discussion.

**Comment by filiptronicek** [comment]
Hi @benz0li 👋!

So, about the two extensions (and probably many more): we don't do pre-releases here in the repo, yet. I think it is an interesting idea to explore in the near future, but for now we always publish the latest stable version of extensions and the introduction of double publishing / one for each channel - stable and prerelease would add a quite large amount of complexity, which probably means it would not work a lot of the time. 

Still a thing worth considering. Thanks for bringing it to our attention.

**Comment by benz0li** [comment]
> [...] but for now we always publish the latest stable version of extensions [...]

Thanks for your prompt reply. I'm not asking about publishing _pre-releases_.

https://open-vsx.org/extension/ms-toolsai/jupyter/2022.3.1000752054 is **not** the latest _stable_ version but a _pre-release_.  
ℹ️ https://open-vsx.org/extension/ms-toolsai/jupyter/2022.2.1010641114 is the latest _stable_ version.

**Comment by filiptronicek** [comment]
> @filiptronicek I'm wondering why version 2022.3.1000752054 has been published as latest.

Oh, sorry for the misunderstanding, I see what you mean. This is a problem with the publishing script, which published it on the 14th of March, because it couldn't change to a release tag, so it started guessing. It took the first commit around the time of the Microsoft release looking for whatever it could find, after that, it just published what it could, this being the `2022.3.1000752054` version. 

I will try to patch this behavior, but it is a bit trickier with these extensions where semver is not used. Thanks for reporting this, I am currently investigating it.

**Comment by filiptronicek** [comment]
This is going to be tricky to solve, since as @benz0li stated, `2022.2.1010641114` is the latest stable version of the extension and this version never appeared in the source code of https://github.com/microsoft/vscode-jupyter, the version in `package.json` is updated ~ once a month. In addition to that, the source code can be the only data source, because although they do publish releases, the last one was in January.

**Comment by benz0li** [comment]
For the time being, I will simply _pin_ the version of this extension.

@filiptronicek Thanks for your detailed feedback. Versioning and publishing on Microsoft's side is utterly obscure.

**Comment by benz0li** [comment]
Your current mechanism for publishing releases of `ms-toolsai.jupyter` seems fine.

I'm going to _pin_ the versions for `ms-toolsai.jupyter` and `ms-python.python` when installing these extensions.
ℹ️ This is required as long as https://github.com/coder/code-server/issues/5031 remains unresolved.
