### ISSUE TITLE
Update Request - Volar extension to version 0.40.5

### ISSUE THREAD

**Issue by ph08n1x** [open-vsx/publish-extensions#634]
Hey guys,
I was wondering if it would be possible to request an update to the Volar VsCodium extension to the newest version (0.40.5)?

Would be greatly appreciated!

**Comment by ph08n1x** [comment]
Ah perfect that's wonderful news! Thank you!

Let me know if you need any support though

**Comment by wvffle** [comment]
Although the issue @filiptronicek linked is still unresolved, it seems like https://open-vsx.org/extension/Vue/volar is already there!

**Comment by filiptronicek** [comment]
Thanks for noting, @wvffle! Seems that magic happened and the internal server issue has been resolved with Volar.

**Comment by filiptronicek** [comment]
@benz0li oh that's expected. We always for every extension try to create the namespace, because it's the easiest way of checking whether it exists or not. For most extensions, it already exists and so it fails -> that is ok since with this step we only want to make sure the namespace exists and if not, create it.
