### ISSUE TITLE
Add eslint-disable-snippets

### ISSUE THREAD

**Issue by jirutka** [open-vsx/publish-extensions#682]
Please add [drKnoxy/eslint-disable-snippets](https://github.com/drKnoxy/eslint-disable-snippets/). The [request issue](https://github.com/drKnoxy/eslint-disable-snippets/issues/9) was opened there a year ago.

**Comment by filiptronicek** [comment]
Hey Jakub (and greetings from Prague!),
I have taken a look at the extension and decided that it would be best to one-time publish it, because it doesn't look like it's receiving further updates. I had to tweak around the `license` field in `package.json` to make Open VSX properly recognize the extension as being MIT-licensed, but at the end it all worked out.

https://open-vsx.org/extension/drKnoxy/eslint-disable-snippets

**Comment by jirutka** [comment]
Ahoj Filipe, také zdravím a díky! :)
