### ISSUE TITLE
Fetching tags vs releases

### ISSUE THREAD

**Issue by apollo13** [open-vsx/publish-extensions#734]
Hi, python isort is a preview extension with the following versions:
https://marketplace.visualstudio.com/items?itemName=ms-python.isort
but open VSX only has:
![image](https://github.com/open-vsx/publish-extensions/assets/81547/fc3b33ad-13c1-4a34-8f78-33a2001907f4)

it would be great if there were parity between the two marketplaces.

**Comment by filiptronicek** [comment]
Hi @apollo13,
https://github.com/microsoft/vscode-isort/releases/tag/v2023.10.1 is according to the source code, indeed the latest stable release of the extension. https://github.com/open-vsx/publish-extensions does not, due to technical limitations and complexity, publish pre-releases. After the release of a next patch or minor version of isort, it should be reflected on https://open-vsx.org as well.
