### ISSUE TITLE
Pulling multiple extensions at once

### ISSUE THREAD

**Issue by blackva** [open-vsx/publish-extensions#81]
Hey! I'd like to gather a good number of extensions and pull them all at once. Quickly going through a few issues and pull requests, I found 2 problems so far:
1. An author of the extension may be against adding it to the registry. If they are and the extension is added, it will cause a lot headache to the maintainers.
As far as I know, there is no way to remove an extension once it is in. Removing extensions from the dataset is also only possible to do manually before commiting if there is already evidance of their opposition.

2. How to reliably determine whether the extension has an appropriate license? It is said that MIT is fine, but I remember reading somewhere Microsoft doesn't permit distribusion of  their extensions in any registry but their, yet their [Debugger for Microsoft Edge](https://marketplace.visualstudio.com/items/msjsdiag.debugger-for-edge/license) is released under MIT. So, if it would be in the dataset, would it be fine or not?

I'll be happy to hear your thoughts on this. It'll be great if there is a chance of making.

**Comment by jankeromnes** [comment]
Hi @blackva! Thanks for sharing your thoughts.

Firstly, please note that this repository is not the OpenVSX registry itself -- it's just a handy publishing CI to quickly upload some open-source extensions to https://open-vsx.org (but there you'll also find some extensions published by other people). We manually verify every extension that is added here (especially checking for a compatible open-source license, namely MIT, ISC, Apache 2, and a few other similar licenses, as determined by the Eclipse Foundation).

> 1. An author of the extension may be against adding it to the registry. If they are and the extension is added, it will cause a lot headache to the maintainers.

That's a good point. However, from what I understand, our assumption was that, if an author is ok with their code & compiled artifacts to be freely distributed and hosted anywhere, it is also ok to compile their code and host it in extension format on https://open-vsx.org (however, if the author is not ok with this, they will likely prevent this by means of a more restrictive license).

> As far as I know, there is no way to remove an extension once it is in.

Actually there is. You can claim ownership, or report abuse, or simply request an extension to be deleted (with a valid reason), and an OpenVSX admin will respond. For example, we've [recently deleted](https://github.com/open-vsx/publish-extensions/pull/78#issuecomment-656026368) all uploaded `markdownlint` extensions, because we had accidentally published broken extensions (now the publishing is fixed, and the newly uploaded version works well).

> 2. How to reliably determine whether the extension has an appropriate license? It is said that MIT is fine, but I remember reading somewhere Microsoft doesn't permit distribusion of their extensions in any registry but their, yet their [Debugger for Microsoft Edge](https://marketplace.visualstudio.com/items/msjsdiag.debugger-for-edge/license) is released under MIT. So, if it would be in the dataset, would it be fine or not?

That is also a good question. My process for reviewing extensions that are proposed for auto-publishing in this repository is:
- Checking the repository `LICENSE` file
- Checking the `"license"` key in `package.json`

If both seem compatible, then it is fine to add this extension to our auto-publish list. However, sometimes a compatible extension (say, MIT license) depends on another extension (say, a Microsoft "do not use with any non-Microsoft product" license), so publishing the MIT-licensed extension will fail, and we cannot add the dependency. So in these cases, we either remove the MIT-licensed, or at least open an issue about the fact that publishing the MIT-licensed extension currently fails (and explain the reason).

For example, I believe that the FSharp extension, which has a compatible license, currently fails to auto-publish to https://open-vsx.org, because it depends on Microsoft's OmniSharp extension, which has an incompatible license and cannot be added to OpenVSX.

Hope this clarifies things a bit. Please let me know if you have other questions.

**Comment by jankeromnes** [comment]
FYI, our current understanding of which open-source licenses are compatible with OpenVSX is:

> The Eclipse Foundation wants to restrict extension licenses to Apache-2.0, EPL-2.0, MIT, ISC, BSD-2-Clause, BSD-3-Clause. Other licenses may be accepted after contacting license@eclipse.org

We have also asked whether GPL-3 could be considered compatible in https://github.com/open-vsx/publish-extensions/issues/49 but haven't yet heard back from Eclipse, so we're holding off on adding GPL-3 licensed extensions for now.

**Comment by jankeromnes** [comment]
> I'd like to gather a good number of extensions and pull them all at once.

That sounds essentially like what consumers of OpenVSX already do (e.g. Theia, Gitpod, VSCodium, Eclipse Che, etc) so this use case sounds fine to me (e.g. downloading `.vsix` files directly from https://open-vsx.org)

**Comment by blackva** [comment]
Thank you for such a detailed reply! Everything you said sounds very optimistic. Just to clarify how an acceptable extension should look like:
- Should have one of the compatible licenses in its package.json, LICENSE file and on the extensions' page in "License" section.
- If it depends on other extension, it's license applies as well. Although, I am not yet sure how to check it. Can you please share the "FSharp" extension? I couldn't find one.
- The extension should be updated 12 month ago at max.

**Comment by blackva** [comment]
Additionally, can you please explain the point of adding version and checkout to the extension's entry. What are the benefits from doing it?

**Comment by jankeromnes** [comment]
> Thank you for such a detailed reply!

You're very welcome! 🙂

> Just to clarify how an acceptable extension should look like:
> 
> - Should have one of the compatible licenses in its package.json, LICENSE file and on the extensions' page in "License" section.

Technically it should have "only compatible licenses" (some extensions have multiple licenses, but if it uses one license that is incompatible, it can't be added to OpenVSX, even if the other licenses are compatible).

Also, I believe the "License" page in Microsoft's Marketplace is just fed from the `license` field in `package.json`. That is the only license that is relevant (e.g. sometimes you have a repository under MIT license, which has a bunch of stuff in it plus a VSCode extension that itself has a different license -- in that case I think only the extension's actual license matters).

> - If it depends on other extension, it's license applies as well. Although, I am not yet sure how to check it.

Maybe I could, but I don't currently check for extension dependencies. My reasoning is that, as long as the main extension is compatible, I can add it, but if it depends on other extensions, then auto-publishing will fail and I will need to check the dependencies. Next, if the dependencies are compatible, I just add them to the auto-publishing list as well, until all the dependencies are met. However, if one of the dependencies has an incompatible license, then it cannot be added, and the publishing of the dependent extensions will continue to fail forever unless the dependency is removed.

> Can you please share the "FSharp" extension? I couldn't find one.

Sure! I meant this one:

https://github.com/open-vsx/publish-extensions/blob/fda76b4c0dc125a4c5e372b417181a31985dc0f3/extensions.json#L376-L382

It's currently in this repository's auto-publish list, however, the nightly publishing job currently fails every day with this error:

```
Error: Cannot resolve dependency: ms-dotnettools.csharp
```

And indeed, `ms-dotnettools.csharp` is itself not on OpenVSX, because its [license](https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt) forbids it. (Note: Even though the OmniSharp respository is itself under MIT license, the extension's `package.json` [explicitly points to](https://github.com/OmniSharp/omnisharp-vscode/blob/6868a02014d91b59c52bb7994f794530a339a35b/package.json#L8) Microsoft's incompatible license.)

Thus, while it was okay to add `Ionide.Ionide-fsharp` to our auto-publish list, publishing can never succeed as long as it depends on an incompatible extension, and that's why you won't find an FSharp extension on https://open-vsx.org today (which is quite sad).

> - The extension should be updated 12 month ago at max. EDIT: it seems there are many extensions that were updated longer than one year ago. I'll be counting these extensions as well if there is no one against it.

I don't think this is relevant. It's cool to auto-publish any extension with a compatible license, even if it wasn't updated in a very long time.

**Comment by jankeromnes** [comment]
> Additionally, can you please explain the point of adding version and checkout to the extension's entry. What are the benefits from doing it?

Sure. FYI, the publishing algorithm is briefly explained [here](https://github.com/open-vsx/publish-extensions#how-are-extensions-published).

- `"version"` only serves to skip publishing if a specific version is already available on https://open-vsx.org (i.e. no need to keep trying to publish the same version over and over if it remains the same), or if a more recent version is already available (this logs a more visible error, because it likely means that someone else than our script is publishing extensions -- e.g. if the maintainer started publishing regular updates, we should remove the extension from our list). For now, `"version"` is totally independent of anything in the extension's repository, and only serves to skip publishing (so omitting it will cause the script to always try publishing)

- `"checkout"` serves to make the publishing script check out a specific Git ref prior to published (e.g. a tag, branch or commit). This is helpful if the extension's default branch serves for development -- you wouldn't want to try and publish a development branch every day. That's why, when a repository has a dedicated release branch, or release tags, we try to use them. If not, then we publish from the default branch and hope the state is good enough (worst case, the maintainer can quickly fix any bugs and bump the extension version, or even better, take over the OpenVSX publishing so that we can remove it from our list)

My heuristic is, if the repository has a dedicated release branch or tags, use that as `"checkout"`. (If it's a specific release tag, I also add `"version"` as a small optimization, in order to only try and publish once.) But if the repository has no release branch or tag, I omit both `"checkout"` and `"version"`.

**Comment by blackva** [comment]
Yes, your reply is definetely very helpful! Thank you!

I made a tool a few days ago and it seems to work fine. The result of the first run, where it was specified to gather only extensions with MIT and Apache-2.0 licenses, it found 2515 extensions. There were some errors and Github went down for a few hours during the process, so it would have had a bit more extensions if everything would be fine. Now I run it with all compatibal licenses you linked above, the run is 80% through, and it has already gathered 3200 extensions. 

The process of checking if extension has a compatible license as follows:

1. Check if extensions is already on OpenVSX. If it is, abort.
2. Check the license on the marketplace. If there is no license or the license is compatible, continue. If there is a license and it does pass the compatibility test, abort. The test is just license.includes('text unique to a compatible license').
3. Check the license in package.json. If there is no license or the license is compatible, continue. If there is no package.json or it has an incompatible license, abort.
4. Check the license detected by Github (aka license information in the about section). If there is no license or it is compatible, continue. If there is a license and it is incompatible, abort.
5. After gathering all this data, check if extension has compatible license in either package.json or the detected license (or in both). If it has, the extension is considered compatible.

The thing I want to change is fourth step. I recently figured out that the detected license has a link to the license file, so it would be better check that file instead.

I will publish the source code when I make a pull request. It should happen in a few days. Yesterday I contacted Eclipes Foundation license@eclipse.org about GPL and quickly got a reply from them. Unfortunaly, they are against publishing extensions with GPL on OpenVSX. 

I just noticed that you also asked EF about this, and I got the same reply as you published at #49 

I don't understand this. When a developer submits their extension to OpenVSX, they don't use its code in their extensions. They use OpenVSX as a service. As a service, OpenVSX can be licensed under any license, but it doesn't matter for the developer. What's matter, though, is its TOS. OpenVSX [links](https://web.archive.org/web/20200620154119/https://open-vsx.org/) to [this](https://web.archive.org/web/20200714045813/https://www.eclipse.org/legal/termsofuse.php) terms of use. 

This made me confused even more. The "License" section contains the following:


By the way, I got reply from license@eclipse-foundation.org, so it is probably better to contant this address in the first place.

**Comment by blackva** [comment]
Yes, your reply is definetely very helpful! Thank you!

I made a tool a few days ago and it seems to work fine. The result of the first run, where it was specified to gather only extensions with MIT and Apache-2.0 licenses, it found 2515 extensions. There were some errors and Github went down for a few hours during the process, so it would have had a bit more extensions if everything would be fine. Now I run it with all compatibal licenses you linked above, the run is 90% through, and it has already gathered 3550 extensions. 

The process of checking if extension has a compatible license as follows:

1. Check if extensions is already on OpenVSX. If it is, abort.
2. Check the license on the marketplace. If there is no license or the license is compatible, continue. If there is a license and it does pass the compatibility test, abort. The test is just license.includes('text unique to a compatible license').
3. Check the license in package.json. If there is no license or the license is compatible, continue. If there is no package.json or it has an incompatible license, abort.
4. Check the license detected by Github (aka license information in the about section). If there is no license or it is compatible, continue. If there is a license and it is incompatible, abort.
5. After gathering all this data, check if extension has compatible license in either package.json or the detected license (or in both). If it has, the extension is considered compatible.

If checking throws an error at any stage, the extension is marked as incompatible.

The thing I want to change is fourth step. I recently figured out that the detected license has a link to the license file, so it would be better check that file instead.

I will publish the source code before making a pull request. It should happen in a few days. Yesterday I contacted Eclipse Foundation license@eclipse.org about GPL and quickly got a reply from them. Unfortunaly, they are against publishing extensions with GPL on OpenVSX. 

I just noticed that you also asked them about this, and I got the same reply as you published at #49 

I don't understand this. When a developer submits their extension to OpenVSX, they don't use its code in their extensions. They use OpenVSX as a service. As a service, OpenVSX can be licensed under any license, but it doesn't matter for the developer. For instanse, anyone using Linux licensed under the GPL doesn't have to publish all their source code under the same license because they use it as a tool and don't add any of its components to their codebase.

What's matter, though, is its TOS. OpenVSX [links](https://web.archive.org/web/20200620154119/https://open-vsx.org/) to [this](https://web.archive.org/web/20200714045813/https://www.eclipse.org/legal/termsofuse.php) terms of use. The "License" section contains the following:

> If Content is licensed to you under license terms and conditions other than the EPL ("Other License") with respect to such Content the term “Contributions “ as used herein shall mean any modifications, enhancements and/or other code and/or documentation related to such Content uploaded, submitted, or otherwise made available by you to the Eclipse Foundation and/or the Members and/or users of this Web site, and such Contributions shall be subject to and governed by the terms and conditions of the Other License. In addition, with regard to such Contributions, you agree to provide the Contributions under the terms and conditions of the EPL, provided however that the Eclipse Foundation shall have the right to reject any Contributions if the acceptance by the Eclipse Foundation would be in any way inconsistent with the Eclipse Foundation's Intellectual Property Policy.

I am neither a lawyer nor native English speaker, so I may understand the text incorrectly. But if the developers have to make all their future contributions under the EPL license, does it mean that majority of extensions that are currently published on OpenVSX break this rule?

I wrote about this to the EF and really hope to get their permission on publishing extensions licensed under the GPL. There are many great extensions with this license. Not allowing publishing extensions with a "wrong open source license" just doesn't sound right.

**Comment by spoenemann** [comment]
@blackva thank you for your enthusiasm on getting many great extensions into Open VSX! However, we are still in the process of transferring the registry to the Eclipse Foundation. The current plan is to have that transfer done by October. When it's done, we will also have automatic checks for extension licenses. For this reason, I think it's ok that the registry contents are currently growing slowly. I would prefer to defer mass contributions to after the transfer to the Eclipse Foundation.

**Comment by blackva** [comment]
@spoenemann Sure. Do you expect making separate TOS for the registry or it is going to be the same as right now?

**Comment by spoenemann** [comment]
The Terms of Use will be the same as now, but those are very generic. In addition, there will be a Publisher Agreement that every extension publisher will have to confirm.

**Comment by blackva** [comment]
> I wrote about this to the EF and really hope to get their permission on publishing extensions licensed under the GPL

More than a week passed and no reply. I don't have patince to wait until October, so I tried switching to vim and it turned out to be a better editor for me. [Here](https://github.com/blackva/vscode-marketplace-scrapper) is the code. I changed it a bit and now it goes through 16k~ extansions in total.
