### ISSUE TITLE
Outdated extensions

### ISSUE THREAD

**Issue by acim** [open-vsx/publish-extensions#91]
eslint in https://open-vsx.org/vscode/gallery is version 2.1.3 while the latest tag in https://github.com/microsoft/vscode-eslint/tags i 2.1.9.

Same is for the following extensions:

ms-azuretools.vscode-docker 1.0.0 -> 1.4.1
redhat.vscode-yaml 0.8.0 -> 0.9.1

**Comment by jankeromnes** [comment]
Good catch! Many thanks @acim for reporting these problems.

> eslint in https://open-vsx.org/vscode/gallery is version 2.1.3 while the latest tag in https://github.com/microsoft/vscode-eslint/tags i 2.1.9.

The namespace `dbaeumer` was claimed by @dbaeumer in https://github.com/eclipse/open-vsx.org/issues/10.

@dbaeumer could you please publish the latest version of `dbaeumer.vscode-eslint` to https://open-vsx.org?*

---

> ms-azuretools.vscode-docker 1.0.0 -> 1.4.1

The namespace `ms-azuretools` was claimed by @fiveisprime in https://github.com/eclipse/open-vsx.org/issues/5.

@fiveisprime could you please publish the latest version of `ms-azuretools.vscode-docker` to https://open-vsx.org?*

---

> redhat.vscode-yaml 0.8.0 -> 0.9.1

The namespace `redhat` was claimed by @fbricon in https://github.com/eclipse/open-vsx.org/issues/6.

@fbricon could you please publish the latest version of `redhat.vscode-yaml` to https://open-vsx.org?*

---

*Publishing to https://open-vsx.org should be as simple as just running `npx ovsx publish` in your repository (with a `OVSX_PAT` access token that you can get [here](https://open-vsx.org/user-settings/tokens)), but please let me know if you run into issues or would like help publishing your extensions to OpenVSX.

**Comment by fbricon** [comment]
I manually pushed https://open-vsx.org/extension/redhat/vscode-yaml/0.9.1 (cc @JPinkney)

**Comment by jankeromnes** [comment]
Awesome, many thanks @fbricon! 💯

**Comment by jankeromnes** [comment]
Ping @dbaeumer @fiveisprime

**Comment by jankeromnes** [comment]
Ok, given that `ms-azuretools.vscode-docker` is now badly outdated [on OpenVSX](https://open-vsx.org/extension/ms-azuretools/vscode-docker) (it's `1.0.0` instead of `1.4.1`), and that it's even [likely broken](https://github.com/VSCodium/vscodium/issues/337#issuecomment-646992291), we probably want to fix this as soon as possible.

In the interest of time, we will temporarily resume publishing `ms-azuretools.vscode-docker` in https://github.com/open-vsx/publish-extensions/pull/108, which should hopefully upload a recent & fixed version of the extension within 24 hours.

@fiveisprime please let us know when you would like to take over the publishing of your extension, and we will be more than happy to help your team set it up and hand over the publishing again.

**Comment by jankeromnes** [comment]
@spoenemann Now that a fixed `ms-azuretools.vscode-docker` version `1.4.1` has been published, could you please delete the likely broken version `1.0.0`?

**Comment by spoenemann** [comment]
Done.

**Comment by jankeromnes** [comment]
We've now resumed auto-publishing of the other two extensions. Everything should be up-to-date again pretty soon.
